# These are supported funding model platforms

github: [ArunKumarBind]
patreon: https://www.patreon.com/c/ArunKumarBind
open_collective: ai-workplace-monitor
ko_fi: arunkumarbind
tidelift: npm/ai-workplace-monitor
community_bridge: ai-workplace-monitor
liberapay: arunkumarbind
issuehunt: arunkumarbind
lfx_crowdfunding: ai-workplace-monitor
polar: arunkumarbind
buy_me_a_coffee: arunkumarbind
thanks_dev: arunkumarbind
custom: ['https://aiworkplace.com/sponsor', 'https://github.com/sponsors/ArunKumarBind']
